#[path = "amuse.pac.rs"]
pub mod amuse_pac;
#[path = "amuse.pgd.rs"]
pub mod amuse_pgd;
#[path = "anim.dat.rs"]
pub mod anim_dat;
#[path = "anim.eog.rs"]
pub mod anim_eog;
#[path = "anim.gax.rs"]
pub mod anim_gax;
#[path = "anim.pck.rs"]
pub mod anim_pck;
pub mod arc;
#[path = "bgi.arc.rs"]
pub mod bgi_arc;
#[path = "bgi.cbg.rs"]
pub mod bgi_cbg;
#[path = "bgi.dsc.rs"]
pub mod bgi_dsc;
pub mod bmp;
#[path = "candysoft.fpk.rs"]
pub mod candysoft_fpk;
#[path = "entis.eri.rs"]
pub mod entis_eri;
#[path = "entis.noa.rs"]
pub mod entis_noa;
pub mod exe;
#[path = "exhibit.gyu.rs"]
pub mod exhibit_gyu;
#[path = "favorite.bin.rs"]
pub mod favorite_bin;
#[path = "favorite.hzc.rs"]
pub mod favorite_hzc;
pub mod int;
#[path = "lilim.aos.rs"]
pub mod lilim_aos;
#[path = "nexas.pac.rs"]
pub mod nexas_pac;
pub mod ogg;
pub mod pfs;
pub mod pna;
#[path = "siglus.g00.rs"]
pub mod siglus_g00;
#[path = "siglus.nwa.rs"]
pub mod siglus_nwa;
#[path = "siglus.omv.rs"]
pub mod siglus_omv;
#[path = "siglus.ovk.rs"]
pub mod siglus_ovk;
#[path = "siglus.owp.rs"]
pub mod siglus_owp;
#[path = "will.arc.rs"]
pub mod will_arc;
pub mod xp3;
pub mod ypf;
#[path = "yuka.ykc.rs"]
pub mod yuka_ykc;
#[path = "yuka.ykg.rs"]
pub mod yuka_ykg;
#[path = "yuka.yks.rs"]
pub mod yuka_yks;

pub mod ptr;
