#[path = "alicesoft.afa.rs"]
pub mod alicesoft_afa;
#[path = "alma.pak.rs"]
pub mod alma_pak;
#[path = "amuse.pac.rs"]
pub mod amuse_pac;
#[path = "anim.dat.rs"]
pub mod anim_dat;
#[path = "anim.eog.rs"]
pub mod anim_eog;
#[path = "anim.gax.rs"]
pub mod anim_gax;
#[path = "anim.pck.rs"]
pub mod anim_pck;
#[path = "artemis.pfs.rs"]
pub mod artemis_pfs;
#[path = "bgi.arc.rs"]
pub mod bgi_arc;
pub mod bmp;
#[path = "candysoft.fpk.rs"]
pub mod candysoft_fpk;
#[path = "candysoft.kg.rs"]
pub mod candysoft_kg;
#[path = "circus.pcm.rs"]
pub mod circus_pcm;
#[path = "escude.bin.rs"]
pub mod escude_bin;
pub mod exe;
#[path = "favorite.bin.rs"]
pub mod favorite_bin;
#[path = "favorite.hzc.rs"]
pub mod favorite_hzc;
#[path = "gesen18.scs.rs"]
pub mod gesen18_scs;
pub mod int;
pub mod kirikiri;
#[path = "kirikiri.xp3.rs"]
pub mod kirikiri_xp3;
#[path = "lilim.aos.rs"]
pub mod lilim_aos;
#[path = "lusterise.med.rs"]
pub mod lusterise_med;
#[path = "nexas.pac.rs"]
pub mod nexas_pac;
pub mod png;
#[path = "siglus.g00.rs"]
pub mod siglus_g00;
#[path = "siglus.ovk.rs"]
pub mod siglus_ovk;
#[path = "siglus.owp.rs"]
pub mod siglus_owp;
#[path = "silky.arc.rs"]
pub mod silky_arc;
#[path = "valkyria.dat.rs"]
pub mod valkyria_dat;
#[path = "willplus.arc.rs"]
pub mod willplus_arc;
#[path = "willplus.pna.rs"]
pub mod willplus_pna;
#[path = "yuka.ykc.rs"]
pub mod yuka_ykc;
#[path = "yuka.ykg.rs"]
pub mod yuka_ykg;
#[path = "yuka.yks.rs"]
pub mod yuka_yks;
#[path = "yuris.ypf.rs"]
pub mod yuris_ypf;

#[path = "shionn.lzss.rs"]
pub mod shionn_lzss;
#[path = "shionn.readwrite.rs"]
pub mod shionn_readwrite;
#[path = "shionn.stream.rs"]
pub mod shionn_stream;
